//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadersHub.ProductAnalyzer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AKIAJKMXHZJWMNZT24HQ")]
        public string ACCESS_KEY_ID {
            get {
                return ((string)(this["ACCESS_KEY_ID"]));
            }
            set {
                this["ACCESS_KEY_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("seEPq5n+KJM0F9yPlawzAHXHwgnw27xmUdAFuQRs")]
        public string SECRET_KEY {
            get {
                return ((string)(this["SECRET_KEY"]));
            }
            set {
                this["SECRET_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mws.amazonservices.co.uk")]
        public string MWS_DESTINATION {
            get {
                return ((string)(this["MWS_DESTINATION"]));
            }
            set {
                this["MWS_DESTINATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AHKGANS7P4NWZ")]
        public string SELLER_ID {
            get {
                return ((string)(this["SELLER_ID"]));
            }
            set {
                this["SELLER_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A1F83G8C2ARO7P")]
        public string MARKETPLACE_ID {
            get {
                return ((string)(this["MARKETPLACE_ID"]));
            }
            set {
                this["MARKETPLACE_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FEEDBACK_COUNT {
            get {
                return ((int)(this["FEEDBACK_COUNT"]));
            }
            set {
                this["FEEDBACK_COUNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FEEDBACK_RATING {
            get {
                return ((int)(this["FEEDBACK_RATING"]));
            }
            set {
                this["FEEDBACK_RATING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>New</string>
  <string>Used - Like New</string>
  <string>Used - Very Good</string>
  <string>Used - Good</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SUB_CONDITION {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SUB_CONDITION"]));
            }
            set {
                this["SUB_CONDITION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double REMAINING_TOKEN {
            get {
                return ((double)(this["REMAINING_TOKEN"]));
            }
            set {
                this["REMAINING_TOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime REQUEST_RESTART_DATE {
            get {
                return ((global::System.DateTime)(this["REQUEST_RESTART_DATE"]));
            }
            set {
                this["REQUEST_RESTART_DATE"] = value;
            }
        }
    }
}
