//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadersHub.MongoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed_Temp
    {
        public long Id { get; set; }
        public string SKU { get; set; }
        public string ASIN { get; set; }
        public string Condition { get; set; }
        public decimal Price { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Status { get; set; }
        public string Seller_Id { get; set; }
    }
}
