//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadersHub.MongoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Price
    {
        public int Id { get; set; }
        public int Product_Id { get; set; }
        public int Store_Id { get; set; }
        public Nullable<decimal> Min_New_ISBN_Price_Dollar { get; set; }
        public Nullable<decimal> Min_Used_ISBN_Price_Dollar { get; set; }
        public Nullable<decimal> Min_New_ISBN_Price_Pound { get; set; }
        public Nullable<decimal> Min_Used_ISBN_Price_Pound { get; set; }
        public Nullable<decimal> Min_New_ASIN_Price_Dollar { get; set; }
        public Nullable<decimal> Min_Used_ASIN_Price_Dollar { get; set; }
        public Nullable<decimal> Min_New_ASIN_Price_Pound { get; set; }
        public Nullable<decimal> Min_Used_ASIN_Price_Pound { get; set; }
        public Nullable<bool> Is_Fixed_New_Dollar { get; set; }
        public Nullable<bool> Is_Fixed_Used_Dollar { get; set; }
        public Nullable<bool> Is_Fixed_New_Pound { get; set; }
        public Nullable<bool> Is_Fixed_Used_Pound { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
