//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadersHub.Mailing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReadersHub.Mailing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      Dear #name#
        ///
        ///I hope you have received your order. If have not received it yet, please let me know so I can resolve the problem for you.
        ///
        ///I really appreciate your business and look forward to doing business with you again. I would be grateful if you would take a moment to leave me feedback the link below. Your positive feedback allows us to keep selling books.
        ///
        ///https://www.amazon.co.uk/gp/feedback/leave-consolidated-feedback.html?ie=UTF8&amp;isCBA=&amp;marketplaceID=A1F83G8C2ARO7P&amp;mode=eligibility&amp;orderID=#o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailTemplate {
            get {
                return ResourceManager.GetString("MailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hi &lt;strong&gt;#name#,&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;Thank you for your order.&lt;/p&gt;
        ///&lt;p&gt;Customer satisfaction is really important to us so if there are any issues with your order, please &lt;a href=&quot;https://www.amazon.co.uk/ss/help/contact/ref=oh_aui_cs_o00_s00?_encoding=UTF8&amp;orderID=#orderId#&amp;sellerID=AHKGANS7P4NWZ&quot;&gt; get in touch&lt;/a&gt; so we have an opportunity to resolve them.&lt;/p&gt;
        ///&lt;p&gt;Would you have 10 seconds to share your recent experience on Amazon with others? &lt;br /&gt;&lt;a href=&quot;http://www.amazon.co.uk/gp/feedback/email-exce [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailTemplatePowerseller {
            get {
                return ResourceManager.GetString("MailTemplatePowerseller", resourceCulture);
            }
        }
    }
}
